export const AUTH_REQUEST = 'auth/request'
export const AUTH_ERROR = 'auth/error'
export const AUTH_REGISTER_SUCCESS = 'auth/registerSuccess'
export const AUTH_LOGIN_SUCCESS = 'auth/loginSuccess'
export const AUTH_RESET = 'auth/loginreset'
export const UPDATE_USER = 'auth/updateUser'