import { Inter } from '@next/font/google';
import Navbar from "../components/Navbar.jsx";
import Head from "next/head";
import HeroSection from '../components/HeroSection.jsx';
import { SubscriptionPlans } from '../components/SubscriptionPlans.jsx';
import Footer from '../components/Footer.jsx';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Next In</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <HeroSection/>
      <SubscriptionPlans/>
      <Footer/>
    </>
  )
}
